(function(){
  const form=document.querySelector('#calculator-form'), adjustments=document.querySelector('#adjustments'), errors=document.querySelector('#form-errors'), results=document.querySelector('#results');
  const money=n=>new Intl.NumberFormat('es-GT',{style:'currency',currency:'GTQ',minimumFractionDigits:2}).format(n).replace('GTQ','Q');
  function adjustmentRow(){const year=new Date().getFullYear();return `<fieldset class="adjustment"><button type="button" class="remove" aria-label="Quitar año">×</button><legend>Registro anual</legend><div class="fields four"><label>Año <input required type="number" name="adjustmentYear" min="2016" max="2026" value="${year}"></label><label>Días salario pendiente <input type="number" name="pendingDays" min="0" value="0"></label><label>Días de reajuste <input type="number" name="adjustmentDays" min="0" value="0"></label><label>Salario pagado/mes (Q) <input type="number" name="paidSalary" min="0" step=".01" value="0"></label><label>¿Recibió bono incentivo? <select name="bonusReceived"><option value="si">Sí</option><option value="no">No</option></select></label></div></fieldset>`;}
  document.querySelector('#add-adjustment').addEventListener('click',()=>adjustments.insertAdjacentHTML('beforeend',adjustmentRow()));
  adjustments.addEventListener('click',e=>{if(e.target.closest('.remove'))e.target.closest('.adjustment').remove()});
  function updateAdjustmentDays(){const start=form.querySelector('[name=startDate]').value,end=form.querySelector('[name=endDate]').value,last=form.querySelector('[name=lastSalaryPaid]').value;const field=form.querySelector('[name=salaryAdjustmentDays]');if(!field)return;if(!end||!start){field.value=0;return}const from=new Date(`${last&&last>start?last:start}T00:00:00`),to=new Date(`${end}T00:00:00`);field.value=Math.max(0,Math.round((to-from)/86400000));}
  ['startDate','endDate','lastSalaryPaid'].forEach(name=>form.querySelector(`[name=${name}]`).addEventListener('change',updateAdjustmentDays));
  function data(){const fd=new FormData(form), v=Object.fromEntries(fd.entries());v.adjustments=[...adjustments.querySelectorAll('.adjustment')].map(row=>({year:row.querySelector('[name=adjustmentYear]').value,pendingDays:row.querySelector('[name=pendingDays]').value,adjustmentDays:row.querySelector('[name=adjustmentDays]').value,paidSalary:row.querySelector('[name=paidSalary]').value,bonusReceived:row.querySelector('[name=bonusReceived]').value}));return v;}
  function line(label,value,reference,referential=false){const shown=value===null?'No aplica':money(value);return `<article class="result-line"><div><h3>${label}</h3>${referential?'<small>Estimación referencial</small>':''}</div><strong>${shown}</strong>${reference?`<p class="result-note">${reference}</p>`:''}</article>`;}
  function show(r,d){const v=r.values,total=Object.values(v).filter(x=>x!==null).reduce((s,x)=>s+x,0);const formula=`Base ${money(r.base)} × 14 ÷ 12 ÷ 365 × ${r.tenure.days} días`;
    const bonusDays=Math.max(0,+d.bonusPendingDays||0);
    const salaryDaily=r.base/30;
    const activityLabel={agricola:'Agrícola',noAgricola:'No agrícola',maquila:'Exportación y maquila'}[d.activity]||d.activity;
    const regionLabel=d.circumscription==='ce1'?'CE1':'CE2';
    const vacationExplanation=`Fecha inicial: ${r.vacation.periodStart.toLocaleDateString('es-GT')}. Fecha final: ${d.endDate}. Días del período: ${r.vacation.periodDays}. Días anuales: 15. Días generados: ${r.vacation.generated.toFixed(5)}. Días gozados: ${r.vacation.taken}. Días pendientes: ${r.vacation.pending.toFixed(5)}. Salario promedio: ${money(r.average)}. Fórmula: ${money(r.average)} ÷ 30 × 15 × ${r.vacation.periodDays} ÷ 365. Resultado: ${money(r.vacation.amount)}.`;
    const aguinaldoExplanation=`Fecha inicial: ${r.aguinaldoStart.toLocaleDateString('es-GT')}. Fecha final: ${d.endDate}. Días del período: ${r.aguinaldoDays}. Salario promedio: ${money(r.average)}. Fórmula: ${r.aguinaldoDays} × ${money(r.average)} ÷ 365 = ${money(v.aguinaldo)}.`;
    const bono14Explanation=`Fecha inicial: ${r.bonoStart.toLocaleDateString('es-GT')}. Fecha final: ${d.endDate}. Días del período: ${r.bono14Days}. Salario promedio: ${money(r.average)}. Fórmula: ${r.bono14Days} × ${money(r.average)} ÷ 365 = ${money(v.bono14)}.`;
    results.innerHTML=`<div class="results-head"><p class="kicker">RESULTADOS</p><h2>Estimación preliminar</h2><p>Tiempo laborado: <strong>${r.tenure.label}</strong><br>Días corridos: <strong>${r.tenure.days}</strong></p>${d.sector!=='privado'?'<p class="warning">Las reglas del MVP se enfocan en el sector privado. Verificá este resultado.</p>':''}</div><div class="result-list">${line('Indemnización',v.indemnizacion,v.indemnizacion===null?'No aplica: el motivo indicado no es despido injustificado.':'Referencia: artículo 82, literal b), del Código de Trabajo.')} ${line('Vacaciones',v.vacaciones,'Referencia: artículo 134 del Código de Trabajo.')} ${line('Aguinaldo',v.aguinaldo,'Referencia: Decreto número 76-78 del Congreso de la República de Guatemala.')} ${line('Bono 14',v.bono14,'Referencia: Decreto número 42-92 del Congreso de la República de Guatemala.')} ${line('Salarios pendientes',v.salariosPendientes,'Referencia normativa: pendiente de validación jurídica específica.')} ${line('Ventajas económicas',v.ventajas,d.economicAdvantages==='si'?'Referencia normativa: pendiente de validación jurídica específica.':'No se indicaron ventajas económicas.')} ${line('Ajuste salarial',v.ajusteSalarial,'Referencia normativa: pendiente de validación jurídica específica.')} ${line('Ajuste bonificación incentivo',v.ajusteBonificacion,'Referencia: Decreto número 37-2001 del Congreso de la República de Guatemala.')} ${line('Bonificación incentivo pendiente',v.bonificacionPendiente,d.bonusStatus==='recibida'?'Se indicó que fue recibida.':'Referencia: Decreto número 37-2001 del Congreso de la República de Guatemala.',d.bonusStatus==='desconocida')} ${line('Horas extraordinarias pendientes',v.horasExtra,'Referencia: artículo 121 del Código de Trabajo.')}</div><div class="total"><span>TOTAL ESTIMADO</span><strong>${money(total)}</strong></div>${history(r)}<div class="contact"><h3>¿Necesitás orientación sobre tu situación laboral?</h3><a class="contact-btn" href="index.html#/ayuda">Contactá a ATRAHDOM</a></div>`;
  }
  function history(r){if(!r.rows.length)return '';return `<section class="history"><h3>Tabla de ajustes históricos</h3><div class="scroll"><table><thead><tr><th>Año</th><th>Días</th><th>Salario mínimo</th><th>Diferencia</th><th>Bono</th></tr></thead><tbody>${r.rows.map(x=>x.missing?`<tr><td>${x.year}</td><td colspan="4">Requiere definición: no hay salario configurado.</td></tr>`:`<tr><td>${x.year}</td><td>${x.pendingDays||0}</td><td>${money(x.min.monthly)}</td><td>${money(x.difference)}</td><td>${money(x.bonusDifference)}</td></tr>`).join('')}</tbody></table></div></section>`;}
  form.addEventListener('submit',e=>{e.preventDefault();errors.textContent='';if(!form.reportValidity())return;if(!form.querySelector('[name=vacationLastPaid]').value)form.querySelector('[name=vacationTaken]').value=0;const d=data();if(new Date(d.endDate)<new Date(d.startDate)){errors.textContent='Revisá los datos: la fecha de terminación no puede ser anterior a la fecha de inicio.';return}if(d.vacationLastPaid&&new Date(d.vacationLastPaid)>new Date(d.endDate)){errors.textContent='La fecha del último período de vacaciones no puede ser posterior a la terminación.';return}if(+d.vacationTaken<0){errors.textContent='Los días de vacaciones gozadas no pueden ser negativos.';return}show(Prestaciones.calculate(d),d);results.scrollIntoView({behavior:'smooth',block:'start'});});
})();
