(function(){
  const form=document.querySelector('#calculator-form'), adjustments=document.querySelector('#adjustments'), errors=document.querySelector('#form-errors'), results=document.querySelector('#results');
  const money=n=>new Intl.NumberFormat('es-GT',{style:'currency',currency:'GTQ',minimumFractionDigits:2}).format(n).replace('GTQ','Q');
  function adjustmentRow(){const year=new Date().getFullYear();return `<fieldset class="adjustment"><button type="button" class="remove" aria-label="Quitar año">×</button><legend>Registro anual</legend><div class="fields four"><label>Año <input required type="number" name="adjustmentYear" min="2016" max="2026" value="${year}"></label><label>Meses salario pendiente <input type="number" name="unpaidMonths" min="0" max="12" value="0"></label><label>Meses a ajustar <input type="number" name="adjustmentMonths" min="0" max="12" value="0"></label><label>Salario pagado/mes (Q) <input type="number" name="paidSalary" min="0" step=".01" value="0"></label><label>¿Recibió bono incentivo? <select name="bonusReceived"><option value="si">Sí</option><option value="no">No</option></select></label></div></fieldset>`;}
  document.querySelector('#add-adjustment').addEventListener('click',()=>adjustments.insertAdjacentHTML('beforeend',adjustmentRow()));
  adjustments.addEventListener('click',e=>{if(e.target.closest('.remove'))e.target.closest('.adjustment').remove()});
  function updateAdjustmentDays(){const start=form.querySelector('[name=startDate]').value,end=form.querySelector('[name=endDate]').value,last=form.querySelector('[name=lastSalaryPaid]').value;const field=form.querySelector('[name=salaryAdjustmentDays]');if(!field)return;if(!end||!start){field.value=0;return}const from=new Date(`${last&&last>start?last:start}T00:00:00`),to=new Date(`${end}T00:00:00`);field.value=Math.max(0,Math.round((to-from)/86400000));}
  ['startDate','endDate','lastSalaryPaid'].forEach(name=>form.querySelector(`[name=${name}]`).addEventListener('change',updateAdjustmentDays));
  function data(){const fd=new FormData(form), v=Object.fromEntries(fd.entries());v.adjustments=[...adjustments.querySelectorAll('.adjustment')].map(row=>({year:row.querySelector('[name=adjustmentYear]').value,unpaidMonths:row.querySelector('[name=unpaidMonths]').value,adjustmentMonths:row.querySelector('[name=adjustmentMonths]').value,paidSalary:row.querySelector('[name=paidSalary]').value,bonusReceived:row.querySelector('[name=bonusReceived]').value}));return v;}
  function line(label,value,explanation,referential=false){const shown=value===null?'No aplica':money(value);return `<article class="result-line"><div><h3>${label}</h3>${referential?'<small>Estimación referencial</small>':''}</div><strong>${shown}</strong>${explanation?`<details><summary>¿Cómo se calculó?</summary><p>${explanation}</p></details>`:''}</article>`;}
  function show(r,d){const v=r.values,total=Object.values(v).filter(x=>x!==null).reduce((s,x)=>s+x,0);const formula=`Base ${money(r.base)} × 14 ÷ 12 ÷ 365 × ${r.tenure.days} días`;
    const bonusMonths=d.bonusMonths!==''&&d.bonusMonths!=null?Math.max(0,Math.floor(+d.bonusMonths)):Math.floor(r.tenure.days/30);
    results.innerHTML=`<div class="results-head"><p class="kicker">RESULTADOS</p><h2>Estimación preliminar</h2><p>Tiempo laborado: <strong>${r.tenure.label}</strong><br>Días corridos: <strong>${r.tenure.days}</strong></p>${d.sector!=='privado'?'<p class="warning">Las reglas del MVP se enfocan en el sector privado. Verificá este resultado.</p>':''}</div><div class="result-list">${line('Indemnización',v.indemnizacion,v.indemnizacion===null?'No aplica: el motivo indicado no es despido injustificado.':formula)}${line('Vacaciones',v.vacaciones,`Base ${money(r.base)}; ${d.vacationDays||15} días anuales, menos días gozados. Se considera el límite de los últimos cinco años.`)}${line('Aguinaldo',v.aguinaldo,`Base ${money(r.base)} ÷ 365 × días desde el último período indicado.`)}${line('Bono 14',v.bono14,`Promedio ${money(r.average)} ÷ 365 × días desde el último período indicado.`)}${line('Salarios pendientes',v.salariosPendientes,'Meses completos indicados × salario mínimo mensual de cada año.')}${line('Ventajas económicas',v.ventajas,d.economicAdvantages==='si'?`${money(r.ordinaryCommissions)} × 30%.`:'No se indicaron ventajas económicas.')}${line('Ajuste salarial',v.ajusteSalarial,`(${money(r.currentMinimum.monthly)} mínimo ordinario vigente 2026 − ${money(+d.ordinarySalary)} salario ordinario) ÷ 30 × ${r.salaryAdjustmentDays} días pendientes (desde el último salario pagado hasta la terminación). La bonificación incentivo no se incluye.`)}${line('Ajuste bonificación incentivo',v.ajusteBonificacion,'Q250 × meses indicados en los que se señaló que no fue recibida.')}${line('Bonificación incentivo pendiente',v.bonificacionPendiente,d.bonusStatus==='recibida'?'Se indicó que fue recibida.':`Q250 × ${bonusMonths} meses reportados.`,d.bonusStatus==='desconocida')}${line('Horas extraordinarias pendientes',v.horasExtra,`${money(r.base/30)} salario diario ÷ jornada × 1.5 × horas indicadas.`)}</div><div class="total"><span>TOTAL ESTIMADO</span><strong>${money(total)}</strong></div>${history(r)}<div class="contact"><h3>¿Necesitás orientación sobre tu situación laboral?</h3><a class="contact-btn" href="index.html#/ayuda">Contactá a ATRAHDOM</a></div>`;
  }
  function history(r){if(!r.rows.length)return '';return `<section class="history"><h3>Tabla de ajustes históricos</h3><div class="scroll"><table><thead><tr><th>Año</th><th>Meses</th><th>Salario mínimo</th><th>Diferencia</th><th>Bono</th></tr></thead><tbody>${r.rows.map(x=>x.missing?`<tr><td>${x.year}</td><td colspan="4">Requiere definición: no hay salario configurado.</td></tr>`:`<tr><td>${x.year}</td><td>${x.adjustmentMonths||0}</td><td>${money(x.min.monthly)}</td><td>${money(x.difference)}</td><td>${money(x.bonusDifference)}</td></tr>`).join('')}</tbody></table></div></section>`;}
  form.addEventListener('submit',e=>{e.preventDefault();errors.textContent='';if(!form.reportValidity())return;const d=data();if(new Date(d.endDate)<new Date(d.startDate)){errors.textContent='Revisá los datos: la fecha de terminación no puede ser anterior a la fecha de inicio.';return}if(+d.vacationTaken>(+d.vacationDays||15)*5){errors.textContent='Revisá los días de vacaciones gozados.';return}show(Prestaciones.calculate(d),d);results.scrollIntoView({behavior:'smooth',block:'start'});});
})();
